apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
       - name: backend
         image: bharti78/backend:latest

         ports:
          - containerPort: 8080
        
         env: 
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://mysql-service:3306/student_app"

          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
         
          - name: SPRING_DATASOURCE_PASSWORD
            value: "linux"


---
apiVersion: v1
kind: Service
metadata: 
 name: backend-service
spec: 
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP    
